### ISSUE TITLE
Code in header file

### ISSUE THREAD

**Issue by weijuwang** [Chargde-Porcupine/phonebook#1]
Currently all of the phonebook's implementation is in `phonebook.h`, which is a header file. I suggest renaming it to `phonebook.c` and creating a header file for it that declares all the functions; if someone tries to `#include "phonebook.h"` right now it won't work because the compiler may see duplicates of each function.

**Comment by epshteinmatthew** [comment]
Suggestion Accepted. I'll do this once the main stuff is actually done.

**Comment by weijuwang** [comment]
Done
